site_name: 'HummerRisk 文档'
site_url: 'https://docs.hummerrisk.com'
site_author: 'Harris'
site_description: 'HummerRisk 是开源的云原生安全检测平台'

repo_name: 'HummerRisk/HummerRisk'
repo_url: 'https://github.com/HummerRisk/HummerRisk.git'
edit_uri: ''
extra_javascript:
  - 'js/baidutongji.js'

theme:
  name: 'material'
  logo: 'img/logo/favicon-反白.png'
  favicon: 'img/logo/favicon-彩色.png'
  language: 'zh'
  palette:
    - scheme: default
      accent: 'red'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      accent: 'red'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font: false
  icon:
    repo: fontawesome/brands/github

nav:
  - 产品介绍: index.md
  - 系统架构: architecture/architecture.md
  - 安装部署:
      - 在 Linux 主机上安装:
          - 安装部署: system/setup-by-fast.md
          - 备份升级: system/upgrade.md
      - 在 K8s 上安装:
          - 安装部署: system/k8s-setup-by-fast.md
          - 备份升级: system/k8s-upgrade.md
  - 功能手册:
      - 使用流程: user/process.md
      - 首页: user/dashboard.md
      - 混合云安全:
          - 多云检测: user/account.md
          - 漏洞检测: user/vuln.md
          - 合规报告: user/report.md
          - 操作审计: user/event.md
      - 云原生安全:
          - 资源态势: user/situation.md
          - 主机检测: user/server.md
          - K8s 检测: user/k8s.md
          - 部署检测: user/config.md
          - 镜像检测: user/image.md
          - 源码检测: user/code.md
          - SBOM 管理: user/sbom.md
      - 任务编排:
          - 任务列表: user/task.md
          - 任务报告: user/taskReport.md
      - 检测管理:
          - 检测规则: user/rule.md
          - 检测结果: user/resource.md
      - 系统设置: user/settings.md
  - 常见问题:
      - 等级保护: question/grade-protection.md
      - 安全基线: question/cis.md
      - 开启企业微信通知: question/weixin-settings.md
      - 开启钉钉消息通知: question/dingtalk-settings.md
      - 使用过程中遇到的问题: question/account.md
  - 开发文档:
      - 开发手册: question/dev-manual.md
      - 如何自定义云资源检测规则: question/rule.md
      - 自定义阿里云监控规则示例: question/example.md
  - 技术相关:
      - 快速了解镜像漏洞扫描Trivy: question/trivy.md
      - 快速了解AWS安全检测Prowler: question/prowler.md
      - 快速了解漏洞检测Nuclei: question/nuclei.md
      - 快速了解漏洞检测Xray: question/xray.md
      - 快速了解软件包依赖漏洞检测: question/dependency.md
      - 快速了解镜像漏洞检测Grype: question/grype.md
      - 快速了解镜像SBOM检测Syft: question/syft.md
  - 优化建议:
      - 阿里云:
          - RAM 用户 MFA 检测: suggest/aliyun/ram.md
          - CDN 域名 HTTPS 监听检测:  suggest/aliyun/cdn-https.md
          - Disk 磁盘加密状态检测:  suggest/aliyun/disk-encrypt.md
          - ECS 实例公网 IP 检测:  suggest/aliyun/ecs-public-ip.md
          - ECS 实例网络类型检测:  suggest/aliyun/ecs-net-type.md
          - ECS VPC 检测:  suggest/aliyun/ecs-vpc.md
          - EIP 带宽峰值检测:  suggest/aliyun/eip-bandwidth.md
          - MongoDB 实例网络类型检测:  suggest/aliyun/mongodb-net-type.md
          - MongoDB 实例公网访问检测:  suggest/aliyun/mongodb-public-ip.md
          - OSS 防盗链检测:  suggest/aliyun/oss-referer.md
          - OSS 公开写入访问权限检测:  suggest/aliyun/oss-public-write.md
          - OSS 对象存储桶冗余存储检测:  suggest/aliyun/oss-data-redundancy-type.md
          - OSS 公开读取访问权限检测:  suggest/aliyun/oss-public-read.md
          - OSS 存储桶加密检测:  suggest/aliyun/oss-encrypt.md
          - Polardb VPC 检测:  suggest/aliyun/polardb-vpc.md
          - PolarDB 实例网络类型检测:  suggest/aliyun/polardb-net-type.md
          - PolarDB 实例公网访问检测:  suggest/aliyun/polardb-public-ip.md
          - RDS 实例网络类型检测:  suggest/aliyun/rds-net-type.md
          - RDS 实例高可用状态检测:  suggest/aliyun/rds-ha.md
          - RDS 实例公网访问检测:  suggest/aliyun/rds-public-ip.md
          - RDS 实例多可用区检测:  suggest/aliyun/rds-available-zones.md
          - RDS VPC 检测:  suggest/aliyun/rds-vpc.md
          - RDS 实例白名单检测:  suggest/aliyun/rds-white-list.md
          - RDS 实例的访问模式检测:  suggest/aliyun/rds-connection-mode.md
          - Redis 实例网络类型检测:  suggest/aliyun/redis-net-type.md
          - Redis 实例公网访问检测:  suggest/aliyun/redis-public-ip.md
          - SecurityGroup 安全组配置检测:  suggest/aliyun/security-group-config.md
          - SecurityGroup 安全组端口访问检测:  suggest/aliyun/security-group-port.md
          - SecurityGroup 高危安全组检测:  suggest/aliyun/security-group-high-risk-port.md
          - SLB 带宽峰值检测:  suggest/aliyun/slb-bandwidth.md
          - SLB VPC 检测:  suggest/aliyun/slb-vpc.md
          - SLB 公网访问检测:  suggest/aliyun/slb-public-ip.md
          - SLB 负载均衡实例关联到VPC检测:  suggest/aliyun/slb-vpc2.md
          - SLB 负载均衡监听检测:  suggest/aliyun/slb-listener.md
          - SLB 负载均衡HTTPS监听检测:  suggest/aliyun/slb-https.md
          - SLB 负载均衡实例公网IP检测:  suggest/aliyun/slb-public-ip2.md
      - 华为云:
          - ECS 实例公网 IP 检测: suggest/huawei/ecs.md
          - ECS 实例网络类型检测: suggest/huawei/ecs2.md
          - OBS 公开读取访问权限检测: suggest/huawei/obs.md
          - OBS 公开写入访问权限检测: suggest/huawei/obs2.md
          - RDS 实例计费类型检测: suggest/huawei/rds.md
          - RDS 实例磁盘空间检测: suggest/huawei/rds2.md
          - RDS 实例公网访问检测: suggest/huawei/rds3.md
          - RDS 实例网络类型检测: suggest/huawei/rds4.md
          - RDS 实例高可用状态检测: suggest/huawei/rds5.md
          - Disk 磁盘加密状态检测: suggest/huawei/disk.md
          - EIP 带宽峰值检测: suggest/huawei/eip.md
          - ELB 负载均衡 HTTPS 监听检测: suggest/huawei/elb.md
          - ELB 实例关联云服务器组检测: suggest/huawei/elb2.md
          - ELB 实例绑定公网 IP 检测: suggest/huawei/elb3.md
          - Redis 实例公网访问检测: suggest/huawei/redis.md
          - Redis 实例免密码访问检测: suggest/huawei/redis2.md
          - DDS 实例公网访问检测: suggest/huawei/dds.md
          - IAM 用户是否登录保护检测: suggest/huawei/iam.md
          - SecurityGroup 安全组配置检测: suggest/huawei/security-group.md
          - SecurityGroup 高危安全组检测: suggest/huawei/security-group2.md
          - GaussDBForOpenGauss 实例网络类型检测: suggest/huawei/gauss-db-for-open-gauss.md
          - GaussDBForOpenGauss 实例公网访问检测: suggest/huawei/gauss-db-for-open-gauss2.md
          - GaussDBForOpenGauss 实例高可用状态检测: suggest/huawei/gauss-db-for-open-gauss3.md
          - GaussDBForOpenGauss 实例磁盘空间检测: suggest/huawei/gauss-db-for-open-gauss4.md
          - GaussDBForOpenGauss 实例计费类型检测: suggest/huawei/gauss-db-for-open-gauss5.md
          - GaussDBForNoSQL 实例网络类型检测: suggest/huawei/gauss-db-for-nosql.md
          - GaussDBForNoSQL 实例计费类型检测: suggest/huawei/gauss-db-for-nosql2.md
          - GaussDBForNoSQL 实例高可用状态检测: suggest/huawei/gauss-db-for-nosql3.md
          - GaussDBForNoSQL 实例公网访问检测: suggest/huawei/gauss-db-for-nosql4.md
          - GaussDBForNoSQL 实例磁盘空间检测: suggest/huawei/gauss-db-for-nosql5.md
          - GaussDB 实例网络类型检测: suggest/huawei/gauss-db.md
          - GaussDB 实例计费类型检测: suggest/huawei/gauss-db2.md
          - GaussDB 实例高可用状态检测: suggest/huawei/gauss-db3.md
          - GaussDB 实例磁盘空间检测: suggest/huawei/gauss-db4.md
          - GaussDB 实例网络类型检测: suggest/huawei/gauss-db5.md
      - 腾讯云:
          - EIP 带宽峰值检测: suggest/tencent/eip-bandwidth.md
          - CVM 实例关机计费模式检测: suggest/tencent/cvm-billing.md
          - CVM 实例公网 IP 检测: suggest/tencent/cvm-public-network-ip.md
          - Redis 实例网络类型检测: suggest/tencent/redis-network-type.md
          - SecurityGroup 配置检测: suggest/tencent/securitygroup-configuration.md
          - SecurityGroup 高危检测: suggest/tencent/securitygroup-highrisk-configuration.md
          - CDB 实例网络类型检测: suggest/tencent/cdb-network-type.md
          - CDB 实例高可用状态检测: suggest/tencent/cdb-ha-status.md
          - CDB 实例公网访问检测: suggest/tencent/cdb-public-network-access.md
          - CDB 实例多可用区检测: suggest/tencent/cdb-multiAZ.md
          - COS 公开读取访问权限检测: suggest/tencent/cos-public-read-access-permission.md
          - CLB 带宽峰值检测: suggest/tencent/clb-bandwidth.md
          - CLB 公网访问检测: suggest/tencent/clb-public-network-access.md
          - CLB 负载均衡实例VPC检测: suggest/tencent/clb-associated-with-vpc.md
          - Disk 磁盘加密检测: suggest/tencent/disk-encryption.md
          - MongoDB 实例网络类型检测: suggest/tencent/mongo-instance-network-type.md
          - MongoDB 实例公网访问检测: suggest/tencent/mongo-public-network.md
          - COS 防盗链检测: suggest/tencent/cos-antileech.md
          - COS 公开写入访问权限检测: suggest/tencent/public-write-access-permission.md
          - COS 存储桶加密检测: suggest/tencent/cos-bucket-encryption.md
      - AWS:
          - AWS S3 全局访问检测: suggest/aws/aws-s3-global-grants.md
          - AWS S3 公开读写访问权限检测: suggest/aws/aws-s3-public-access.md
          - AWS EC2 实例关机状态检测: suggest/aws/aws-stopped-instance.md
          - AWS EBS 未使用检测: suggest/aws/aws-ebs-unattached.md
          - AWS EC2 标签规范检测: suggest/aws/aws-ec2-tagged.md
      - Azure:
          - 弹性 IP: suggest/azure/gauss-db-for-open-gauss.md
      - GCP:
          - 弹性 IP: suggest/gcp/gauss-db-for-open-gauss.md
      - VMware:
          - VMware vSphere Host 电源状态检测: suggest/vsphere/host.md
          - VMware vSphere Host 连接状态检测: suggest/vsphere/host2.md
          - VMware vSphere Datacenter 关联资源检测: suggest/vsphere/datacenter.md
          - VMware vSphere ResourcePool CPU 内存检测: suggest/vsphere/resource-pool.md
          - VMware vSphere Network 分布式类型检测: suggest/vsphere/network.md
          - VMware vSphere VM 状态检测: suggest/vsphere/vm.md
          - VMware vSphere Cluster 高可用状态检测: suggest/vsphere/cluster.md
          - VMware vSphere Datastore 多主机访问检测: suggest/vsphere/datastore.md
          - VMware vSphere Datastore 可用空间检测: suggest/vsphere/datastore2.md
          - VMware vSphere Datastore 精简配置检测: suggest/vsphere/datastore3.md
      - OpenStack:
          - OpenStack 网络状态检测: suggest/openstack/network.md
          - OpenStack 项目成员检测: suggest/openstack/project.md
          - OpenStack 实例类型检测: suggest/openstack/server.md
          - OpenStack 镜像状态检测: suggest/openstack/image.md
          - OpenStack SecurityGroups 安全组配置检测: suggest/openstack/security-groups.md
      - 百度云:
          - CDN 域名 HTTPS 监听检测: suggest/baidu/cdn-domain-https-monitoring.md
          - BCC 实例公网 IP 监测: suggest/baidu/bcc-public-network-ip-monitoring.md
          - BCC 实例网络类型检测: suggest/baidu/bcc-network-type.md
          - 普通型负载公网 IP 绑定扫描: suggest/baidu/common-public-network-ip.md
          - EIP 带宽峰值检测: suggest/baidu/eip-bandwidth.md
          - 磁盘加密状态检测: suggest/baidu/disk-encryption.md
          - BCC VPC 检测: suggest/baidu/bcc-vpc.md
          - BBC 实例公网IP检测: suggest/baidu/bcc-public-network-ip.md
          - 应用型负载公网 IP 绑定扫描: suggest/baidu/alb-public-network-ip.md
          - BBC 实例带宽检测: suggest/baidu/bcc-bandwidth.md
          - SecurityGroup 安全组端口访问: suggest/baidu/securityGroup-port-access.md
      - 火山引擎:
          - CDN 域名 HTTPS 监听检测: suggest/volc/cdn-https.md
          - ECS VPC 检测: suggest/volc/ecs-vpc.md
          - ECS 实例网络类型检测: suggest/volc/ecs-net-type.md
          - ECS 实例公网IP检测: suggest/volc/ecs-public-ip.md
          - EIP 带宽峰值检测: suggest/volc/eip-bandwidth.md
          - MongoDB 实例公网访问检测: suggest/volc/mongodb-public-ip.md
          - MongoDB 实例网络类型检测: suggest/volc/mongodb-net-type.md
          - SecurityGroup 安全组端口访问检测: suggest/volc/securitygroup-port.md
          - SecurityGroup 高危安全组检测: suggest/volc/securitygroup-high-risk-port.md
      - 青云:
          - MySQL 实例网络类型检测: suggest/qingcloud/mysql-network-type.md
          - ECS VPC 检测: suggest/qingcloud/ecs-vpc.md
          - MySQL 实例公网访问检测: suggest/qingcloud/mysql-public-network-access.md
          - MySQL 实例高可用状态检测: suggest/qingcloud/mysql-ha.md
          - ECS 实例公网 IP 检测: suggest/qingcloud/ecs-public-network-ip.md
          - EIP 带宽峰值检测: suggest/qingcloud/eip-bandwidth.md
          - MongoDB 实例公网访问检测: suggest/qingcloud/mongodb-public-network.md
          - ECS 实例网络类型检测: suggest/qingcloud/ecs-network-type.md
          - MongoDB 实例网络类型检测: suggest/qingcloud/mongodb-network-type.md
      - UCloud:
          - UHost 公网IP检测: suggest/ucloud/uhost-public-network-ip.md
          - UHost VPC检测: suggest/ucloud/uhost-vpc.md
          - UHost 网络类型检测: suggest/ucloud/uhost-network-type.md
          - EIP 带宽峰值检测: suggest/ucloud/eip-bandwidth.md
          - UHost 挂载磁盘加密检测: suggest/ucloud/uhost-disk-encryption.md
      - Qiniu:
          - 弹性 IP: suggest/qiniu/gauss-db-for-open-gauss.md
  - 版本迭代:
      - 更新日志: about/changelog.md
      - 更新说明:
          - ReleaseNote 0.3.2: release/release-0.3.2.md
          - ReleaseNote 0.3.1: release/release-0.3.1.md
          - ReleaseNote 0.3.0: release/release-0.3.0.md
          - ReleaseNote 0.2.2: release/release-0.2.2.md
          - ReleaseNote 0.2.1: release/release-0.2.1.md
          - ReleaseNote 0.2.0: release/release-0.2.0.md
  - 关于我们:
      - 联系我们: about/contact.md
  - 资源下载: about/download.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  hummerrisk:
    version: v0.3.1
  search:
    separator: '[\s\-\.]+'
    language: 'zh'
    Content-Encoding: gzip
  generator: false
  version:
    default: master
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HummerRisk
    - icon: fontawesome/solid/envelope
      link: mailto:support@hummercloud.com
    - icon: fontawesome/brands/skype
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=yro3zdvticm8J4tdA5Dw20dh028NKeap&jump_from=webapi

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2022 <a href="https://www.hummercloud.com">北京瀚马信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备2022018178号-1</a>
plugins:
  - search
