site_name: 'HummerRisk 文档'
site_url: 'https://docs.hummerrisk.com'
site_author: 'Harris'
site_description: 'HummerRisk 是开源的云原生安全检测平台'

repo_name: 'HummerRisk/HummerRisk'
repo_url: 'https://github.com/HummerRisk/HummerRisk.git'
edit_uri: ''
extra_javascript:
  - 'js/baidutongji.js'

theme:
  name: 'material'
  logo: 'img/logo/favicon-反白.png'
  favicon: 'img/logo/favicon-彩色.png'
  language: 'zh'
  palette:
    - scheme: default
      accent: 'red'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      accent: 'red'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font: false
  icon:
    repo: fontawesome/brands/github

nav:
  - 产品介绍: index.md
  - 系统架构: architecture/architecture.md
  - 安装部署:
      - 在 Linux 主机上安装:
          - 安装部署: system/setup-by-fast.md
          - 备份升级: system/upgrade.md
      - 在 K8s 上安装:
          - 安装部署: system/k8s-setup-by-fast.md
          - 备份升级: system/k8s-upgrade.md
  - 功能手册:
      - 使用流程: user/process.md
      - 首页: user/dashboard.md
      - 混合云安全:
          - 多云检测: user/account.md
          - 漏洞检测: user/vuln.md
          - 合规报告: user/report.md
          - 操作审计: user/event.md
      - 云原生安全:
          - 资源态势: user/situation.md
          - 主机检测: user/server.md
          - K8s 检测: user/k8s.md
          - 部署检测: user/config.md
          - 镜像检测: user/image.md
          - 源码检测: user/code.md
          - SBOM 管理: user/sbom.md
      - 任务编排:
          - 任务列表: user/task.md
          - 任务报告: user/taskReport.md
      - 检测管理:
          - 检测规则: user/rule.md
          - 检测结果: user/resource.md
      - 系统设置: user/settings.md
  - 常见问题:
      - 等级保护: question/grade-protection.md
      - 安全基线: question/cis.md
      - 开启企业微信通知: question/weixin-settings.md
      - 开启钉钉消息通知: question/dingtalk-settings.md
      - 使用过程中遇到的问题: question/account.md
  - 开发文档:
      - 开发手册: question/dev-manual.md
      - 如何自定义云资源检测规则: question/rule.md
      - 自定义阿里云监控规则示例: question/example.md
  - 技术相关:
      - 快速了解镜像漏洞扫描Trivy: question/trivy.md
      - 快速了解AWS安全检测Prowler: question/prowler.md
      - 快速了解漏洞检测Nuclei: question/nuclei.md
      - 快速了解漏洞检测Xray: question/xray.md
      - 快速了解软件包依赖漏洞检测: question/dependency.md
      - 快速了解镜像漏洞检测Grype: question/grype.md
      - 快速了解镜像SBOM检测Syft: question/syft.md
  - 优化建议:
      - 阿里云:
          - RAM 用户 MFA 检测: suggest/aliyun/ram.md
          - 弹性 IP: suggest/aliyun/eip.md
      - 华为云:
          - GaussDBForOpenGauss 实例网络类型检测: suggest/huawei/gaussdbforopengauss.md
          - GaussDBForOpenGauss 实例公网访问检测: suggest/huawei/gaussdbforopengauss2.md
          - GaussDBForOpenGauss 实例高可用状态检测: suggest/huawei/gaussdbforopengauss3.md
          - GaussDBForOpenGauss 实例磁盘空间检测: suggest/huawei/gaussdbforopengauss4.md
          - GaussDBForOpenGauss 实例计费类型检测: suggest/huawei/gaussdbforopengauss5.md
          - GaussDBForNoSql 实例网络类型检测: suggest/huawei/gaussdbfornosql.md
          - GaussDBForNoSQL 实例计费类型检测: suggest/huawei/gaussdbfornosql2.md
          - GaussDBForNoSql 实例高可用状态检测: suggest/huawei/gaussdbfornosql3.md
          - GaussDBForNoSql 实例公网访问检测: suggest/huawei/gaussdbfornosql4.md
          - GaussDBForOpenGauss 实例磁盘空间检测: suggest/huawei/gaussdbfornosql5.md
      - 腾讯云:
          - EIP 带宽峰值检测: suggest/tencent/eip-bandwidth.md
          - CVM 实例关机计费模式检测: suggest/tencent/cvm-billing.md
          - CVM 实例公网IP检测: suggest/tencent/cvm-public-network-ip.md
          - Redis 实例网络类型检测: suggest/tencent/redis-network-type.md
          - SecurityGroup 安全组配置检测: suggest/tencent/securitygroup-configuration.md
          - SecurityGroup 高危安全组检测: suggest/tencent/securitygroup-highrisk-configuration.md
          - CDB 实例网络类型检测: suggest/tencent/cdb-network-type.md
          - CDB 实例高可用状态检测: suggest/tencent/cdb-ha-status.md
          - CDB 实例公网访问检测: suggest/tencent/cdb-public-network-access.md
          - CDB 实例多可用区检测: suggest/tencent/cdb-multiAZ.md
          - COS 公开读取访问权限检测: suggest/tencent/cos-public-read-access-permission.md
          - CLB 带宽峰值检测: suggest/tencent/clb-bandwidth.md
          - CLB 公网访问检测: suggest/tencent/clb-public-network-access.md
          - CLB 负载均衡实例关联到VPC检测: suggest/tencent/clb-associated-with-vpc.md
          - Disk 磁盘加密检测: suggest/tencent/disk-encryption.md
          - MongoDB 实例网络类型检测: suggest/tencent/mongo-instance-network-type.md
          - MongoDB 实例公网访问检测: suggest/tencent/mongo-public-network.md
          - COS 防盗链检测: suggest/tencent/cos-antileech.md
          - COS 公开写入访问权限检测: suggest/tencent/public-write-access-permission.md
          - COS 存储桶加密检测: suggest/tencent/cos-bucket-encryption.md
      - AWS:
          - AWS S3全局访问检测: suggest/aws/aws-s3-global-grants.md
          - AWS S3公开读写访问权限检测: suggest/aws/aws-s3-public-access.md
          - AWS EC2实例关机状态检测: suggest/aws/aws-stopped-instance.md
          - AWS EBS未使用检测: suggest/aws/aws-ebs-unattached.md
          - AWS EC2标签规范检测: suggest/aws/aws-ec2-tagged.md
      - Azure:
          - 弹性 IP: suggest/azure/gaussdbforopengauss.md
      - GCP:
          - 弹性 IP: suggest/gcp/gaussdbforopengauss.md
      - VMware:
          - 弹性 IP: suggest/vsphere/gaussdbforopengauss.md
      - OpenStack:
          - 弹性 IP: suggest/openstack/gaussdbforopengauss.md
      - 百度云:
          - 弹性 IP: suggest/baidu/gaussdbforopengauss.md
      - 火山引擎:
          - 弹性 IP: suggest/volc/gaussdbforopengauss.md
      - 青云:
          - 弹性 IP: suggest/qingcloud/gaussdbforopengauss.md
      - UCloud:
          - 弹性 IP: suggest/ucloud/gaussdbforopengauss.md
      - Qiniu:
          - 弹性 IP: suggest/qiniu/gaussdbforopengauss.md
  - 版本迭代:
      - 更新日志: about/changelog.md
      - 更新说明:
          - ReleaseNote 0.3.2: release/release-0.3.2.md
          - ReleaseNote 0.3.1: release/release-0.3.1.md
          - ReleaseNote 0.3.0: release/release-0.3.0.md
          - ReleaseNote 0.2.2: release/release-0.2.2.md
          - ReleaseNote 0.2.1: release/release-0.2.1.md
          - ReleaseNote 0.2.0: release/release-0.2.0.md
  - 关于我们:
      - 联系我们: about/contact.md
  - 资源下载: about/download.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  hummerrisk:
    version: v0.3.1
  search:
    separator: '[\s\-\.]+'
    language: 'zh'
    Content-Encoding: gzip
  generator: false
  version:
    default: master
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HummerRisk
    - icon: fontawesome/solid/envelope
      link: mailto:support@hummercloud.com
    - icon: fontawesome/brands/skype
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=yro3zdvticm8J4tdA5Dw20dh028NKeap&jump_from=webapi

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2022 <a href="https://www.hummercloud.com">北京瀚马信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备2022018178号-1</a>
plugins:
  - search
